name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

        
        

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: MySQL Deploy Action
  # You may pin to the exact commit or the version.
  # uses: calxus/mysql-deploy-action@54af3465f56d1b95c27c520f3b84693b3646ab0b
      uses: calxus/mysql-deploy-action@v2
      with:
        # Hostname used to connect to database
        DATABASE_HOST: usersdb
        # Port used to connect to database
        DATABASE_PORT: 3306 # optional, default is 3306
        # Name of database to connect to
        DATABASE_NAME: usersdb
        # Username used to connect to database
        DATABASE_USERNAME: usuario
        # Password used to connect to database
        DATABASE_PASSWORD: mamae@123
        # Script run on database
        DATABASE_SCRIPT: estrutura.sql
          

          
    - name: Install dependencies
      run: npm install
    - name: Install cliente mysql
      run: sudo apt install mysql-client
    - name: Configure MySQL permissions
      run: |
        sudo service mysql start
        mysql -P 3306 -h 127.0.0.1 -u usuario -pmamae@123 -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'mamae@123'; FLUSH PRIVILEGES;"
    - name: Criar Tabelas
      run:  sudo mysql -P 3306 -h 127.0.0.1 usersdb -pmamae@123 < estrutura.sql
    - name: Run tests
      run: npm test
