name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          
          MYSQL_ROOT_PASSWORD: mamae@123
          MYSQL_DATABASE: usersdb
        ports:
          - 3306:3306
        
        

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Install cliente mysql
      run: sudo apt install mysql-client
    - name: Configure MySQL permissions
      run: |
        sudo service mysql start
        mysql -h localhost -u root -psenha -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'mamae@123'; FLUSH PRIVILEGES;"
    - name: Criar Tabelas
      run:  sudo mysql -P 3306 -h 127.0.0.1 usersdb -pmamae@123 < estrutura.sql
    - name: Run tests
      run: npm test
