name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: mamae@123
          MYSQL_DATABASE: usersdb
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Start MySQL
      run: sudo /etc/init.d/mysql start
    - name: Install cliente mysql
      run: sudo apt install mysql-client
    - name: Criar Tabelas
      run:  sudo mysql  usersdb < estrutura.sql
    - name: Run tests
      run: npm test
